<?php

class ShopProcessCategory extends Process implements Module, ConfigurableModule {
		
	public static function getModuleInfo() {
		return array(
			'title' => 'Shop: '.__('Category Process', __FILE__),
			'summary' => __('Allows to browse products in category by product properties', __FILE__),
			'version' => 001,
			'permanent' => false,
			'singular' => true,
			'permission' => 'shop-order',
			'requires' => array()
		);
	}
		
	public function init() {

	}
	
	static public function getModuleConfigInputfields(Array $data) {
		// get modules
		$modules = Wire::getFuel('modules');
		// this is a container for fields, basically like a fieldset
		$inputfields = new InputfieldWrapper();
		// where to look
		 		
		return $inputfields;
	}
	
	public function ___execute() {
		if($this->input->urlSegment1) {
			$segments = array();
			$i = 1;
			$segment = 'urlSegment'.$i;
			while($str = $this->input->$segment) {
				$segments[] = $str;
				$i++;
				$segment = 'urlSegment'.$i;
			}
		 	return $this->page->children('template=shop_product, shop_product_manufacturer='.$this->pages->get('name='.$segments[0])->id.', sort=title');
		} else {
			return $this->page->children('template=shop_product, sort=title');
		}
	}
	
	public function ___install() {
		$pages = $this->fuel('pages');
		$fields = $this->fuel('fields');
		$modules = $this->fuel('modules');
		
		$field = new Field();	
		$field->type = $this->fuel('modules')->get("FieldtypeModule"); 
		$field->name = 'shop_category_process';
		$field->label = 'Shop: Category Process';
		$field->moduleTypes = array('Process');
		$field->instantiateModule = true;
		$field->flags = Field::flagSystem;
		$field->save();
		$this->message("Created field: ".$field->name); 
	}
	
	public function ___uninstall() {
		$fields = $this->fuel('fields');
		$field = $fields->get('shop_category_process');
		if($field->id) {
			$name = $field->id;
			$fields->delete($field);
			$this->message("Deleted field: ".$name);
		}
	}	
}
